### ISSUE TITLE
Please help me get `curl` and `wget` onto my machine

### ISSUE THREAD

**Issue by KochTobi** [qbicsoftware/research-data-management#20]
As a scientist working with Windows in the lab, I do not know how to check for `curl` or `wget` on my machine. It is a mystery. Can you provide some helpful information on how to verify that I have the tools on my machine. In case I do not have them please help me and document how and where I can download and install them from.

**Comment by sven1103** [comment]
Honestly, since curl is even officially shipped with Windows 10 and 11 (https://curl.se/windows/microsoft.html), I don't see why it up to us to support here.

We must not started to link external resources, since there is no guarantee they are a) up to date and b) not orphaned at some point.

A simple search via "How to use/install curl on Windows" is getting you there.
